"use client";

import { useState } from "react";
import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import SessionProvider from "./SessionProvider";
import Nav from "@/components/nav";
import { usePathname } from "next/navigation";
import { MobileNavContext } from "@/context/mobile-nav-context";

const inter = Inter({ subsets: ["latin"] });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const page = usePathname();
  const isHomePage = page === "/";

  const [showMobileNav, setShowMobileNav] = useState(false);

  return (
    <html lang="en">
      <MobileNavContext.Provider value={{ showMobileNav }}>
        <body className="bg-gray-200 min-h-screen">
          <SessionProvider>
            <button
              onClick={() => setShowMobileNav(true)}
              className="md:hidden"
            >
              <svg
                xmlns="http://www.w3.org/2000/svg"
                fill="none"
                viewBox="0 0 24 24"
                strokeWidth={1.5}
                stroke="currentColor"
                className="w-6 h-6"
              >
                <path
                  strokeLinecap="round"
                  strokeLinejoin="round"
                  d="M3.75 6.75h16.5M3.75 12h16.5m-16.5 5.25h16.5"
                />
              </svg>
            </button>
            <div className="md:flex">
              {!isHomePage && <Nav />}
              {!isHomePage ? (
                <div className="bg-white flex-grow mt-2 mr-2 mb-2 rounded-lg p-4">
                  {children}
                </div>
              ) : (
                children
              )}
            </div>
          </SessionProvider>
        </body>
      </MobileNavContext.Provider>
    </html>
  );
}
